services:
  db:
    container_name: mysql_usuarios
    image: ${DOCKER_IMAGE_URL:-data_eval2-db:latest}
    build: .
    restart: always
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

